

const CONFIG_THEME_MODE = 'config/CONFIG_THEME_MODE';
const CONFIG_UUID = 'config/CONFIG_UUID';
const CONFIG_ACCESS_TOKEN = 'config/CONFIG_ACCESS_TOKEN';
const CONFIG_ACCOUNT_MODE = 'config/CONFIG_ACCOUNT_MODE';
const CONFIG_REFRESH_TOKEN = 'config/CONFIG_REFRESH_TOKEN';
const CONFIG_USERNAME = 'config/CONFIG_USERNAME';
const CONFIG_LAST_USERNAME = 'config/CONFIG_LAST_USERNAME';
const CONFIG_REGISTER_USERNAME = 'config/CONFIG_REGISTER_USERNAME';
const CONFIG_TOPIC = 'config/CONFIG_TOPIC';
const CONFIG_AVATAR = 'config/CONFIG_AVATAR';
const CONFIG_REFERRAL_CODE = 'config/CONFIG_REFERRAL_CODE';
const CONFIG_REFERRAL_USER = 'config/CONFIG_REFERRAL_USER';
const CONFIG_LAST_ORDER_TYPE = 'config/CONFIG_LAST_ORDER_TYPE';
const CONFIG_LAST_CHART_TYPE = 'config/CONFIG_LAST_CHART_TYPE';
const PRODUCT_ALL = 'all';



const String BOX_CONFIG = 'BOX_CONFIG';
const String BOX_USER = 'BOX_USER';
const String BOX_PRODUCT = 'BOX_PRODUCT';
const String BOX_CONTRACT = 'BOX_CONTRACT';
const String BOX_SYSTEM_CONFIG = 'BOX_SYSTEM_CONFIG';
const String BOX_SYSTEM_BANNER = 'BOX_SYSTEM_BANNER';

